### ISSUE TITLE
MessageBox chopped off with MaxWidth

### ISSUE THREAD

**Issue by NoralK** [AvaloniaUtils/MessageBox.Avalonia#27]
If I have a long message and have MaxWidth set then the button and message get chopped off. The Grid in MessageBoxWindow should have a MaxWidth="{Binding MaxWidth}".

**Comment by frapendev** [comment]
I ran into the same issue and it's frustrating especially because I often have to show long messages. Is there a solution?

**Comment by CreateLab** [comment]
As I see, it's fixed. If no - reopen.
