### ISSUE TITLE
[FEATURE REQUEST] Set default and cancel attribute (ESCAPE and ENTER)

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUtils/MessageBox.Avalonia#36]
It's possible to add defaut and cancel button attributes? So ESCAPE will call cancel (No, Cancel) and ENTER will do default (Yes, OK)

**Comment by CreateLab** [comment]
Check this idea after avalonia 0.10 release.

**Comment by CreateLab** [comment]
https://github.com/AvaloniaUtils/MessageBox.Avalonia/pull/37

**Comment by CreateLab** [comment]
https://www.nuget.org/packages/MessageBox.Avalonia/0.10.4-night

**Comment by CreateLab** [comment]
@sn4k3 add keybindings only for standard window

**Comment by sn4k3** [comment]
Can also do a updated package that compatible with the preview6?
