### ISSUE TITLE
Option to config FontFamily to display CJK characters

### ISSUE THREAD

**Issue by ryancheung** [AvaloniaUtils/MessageBox.Avalonia#38]
MessageBox shows CJK characters as white boxes currently.
Please add an option to set FontFamily to the MessageBox Window for displaying CJK characters correctly.
Thanks.

**Comment by CreateLab** [comment]
it's not supported in Avalonia Textbox at all. Please create issue in avalonia repo, after thay fix it, we fix it in our msbox.

**Comment by ryancheung** [comment]
OK. MessageBox renders message caption and content with TextBox control instead of TextBlock. It's true that Avalonia's TextBox cannot show CJK characters correctly at the moment.
