### ISSUE TITLE
Last word sent to a new line and cut by half on some cases

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUtils/MessageBox.Avalonia#43]
It seens there is a sweet spot for the line break...
3 bad samples and 3 good:

![image](https://user-images.githubusercontent.com/113281/102726546-8b946880-4317-11eb-8fe8-1a972a840a9f.png)
![image](https://user-images.githubusercontent.com/113281/102726581-da420280-4317-11eb-9f94-c0c5a36b4db0.png)
![image](https://user-images.githubusercontent.com/113281/102726638-458bd480-4318-11eb-8bd7-f028c3682c96.png)
![image](https://user-images.githubusercontent.com/113281/102726574-ca2a2300-4317-11eb-8497-37129f9f0f25.png)
![image](https://user-images.githubusercontent.com/113281/102726597-fa71c180-4317-11eb-9140-d50c644b8fd2.png)
![image](https://user-images.githubusercontent.com/113281/102726599-fe054880-4317-11eb-9274-919f1535b14b.png)

**Comment by sn4k3** [comment]
Still have this problem on the newest release. Is there a way to fix it?
![image](https://user-images.githubusercontent.com/113281/106031989-ced8b880-60c7-11eb-936c-c0c36e96e9a5.png)

**Comment by alessandrofrancesconi** [comment]
Same problem, version 1.0.1

**Comment by CreateLab** [comment]
@sn4k3 - as fast fix u may set size for messagebox
---------------------
if u may create mvp with this bug 
it really helps me to fix this bug

**Comment by sn4k3** [comment]
How can i set width? It only allow me to use the MaxWidth.
Btw is possible to expose the Window instance so we can attach the DevTools?

My code:

```
var messageBoxStandardWindow = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(
                new MessageBoxStandardParams
                {
                    ButtonDefinitions = buttons,
                    ContentTitle = title ?? window.Title,
                    ContentMessage = message,
                    Icon = icon,
                    Style = style,
                    WindowIcon = new WindowIcon(App.GetAsset("/Assets/Icons/UVtools.ico")),
                    WindowStartupLocation = location,
                    CanResize = false,
                    MaxWidth = window.GetScreenWorkingArea().Width - UserSettings.Instance.General.WindowsHorizontalMargin,
                    ShowInCenter = true
                });
            return await messageBoxStandardWindow.ShowDialog(window);
```

MaxWidth is never reached since my messages are never longer than my display

**Comment by CreateLab** [comment]
Ок, l'll check

**Comment by CreateLab** [comment]
![image](https://user-images.githubusercontent.com/33497292/106379864-f8435e00-63bf-11eb-9c19-02c3efd0deeb.png)
fix in dev branch

**Comment by sn4k3** [comment]
I can confirm, that worked.
Can you point out the bug? I only saw a margin on icon, is that it?

**Comment by CreateLab** [comment]
> I can confirm, that worked.
> Can you point out the bug? I only saw a margin on icon, is that it?

As real textbox has bug with it's positioning and it's AvaloniaUI bug, but icon margin fix this but, but not heal)

**Comment by Shadow4walker** [comment]
@CreateLab 
still facing this issue in the v1.0.5 with Avalonia v0.10.0 using Fluent Theme I guess because the font is bigger!

my code 

> 
        public static async Task<ButtonResult> ShowMessage(string title, string message, Icon icon, Window window = null, Style style = Style.Windows, ButtonEnum btn = ButtonEnum.Ok)
        {
            var win = window ?? new Window {Topmost = true, ShowInTaskbar = false};
            var msBoxStandardWindow = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(new MessageBoxStandardParams
            {
                CanResize = false,
                ContentTitle = title,
                ContentMessage = message,
                Icon = icon,
                Style = style,
                ShowInCenter = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ButtonDefinitions = btn,

            });

            return await msBoxStandardWindow.ShowDialog(win);
        }
