### ISSUE TITLE
Solve width problem

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUtils/MessageBox.Avalonia#52]
Fix max width, this wrapping text.

**Comment by CreateLab** [comment]
fix min width and fix math width between 200 and 500px
allow wrap text
![изображение](https://user-images.githubusercontent.com/33497292/106603522-71cd7e80-656f-11eb-8c7e-34f5595ba366.png)
now it's not wrapping

**Comment by mlidija** [comment]
Hi, any updates/progress on this issue?

**Comment by alessandrofrancesconi** [comment]
I've started to see this issue after upgrading from 1.1.1 to 1.1.2

**Comment by CreateLab** [comment]
@mlidija  @alessandrofrancesconi  nope, 1.1.2 just fix enums.
Now i have no ideas how to fix this problem. And `need help`

**Comment by alessandrofrancesconi** [comment]
> @mlidija @alessandrofrancesconi nope, 1.1.2 just fix enums.
> Now i have no ideas how to fix this problem. And `need help`

I don't think it's "_just fix enums_", look:

1.1.1:

![image](https://user-images.githubusercontent.com/1595223/115468605-9d3d3c80-a233-11eb-85ad-ca79e7123e56.png)

right after 1.1.2:

![image](https://user-images.githubusercontent.com/1595223/115468344-40418680-a233-11eb-9991-4ec9f524000a.png)

**Comment by CreateLab** [comment]
@alessandrofrancesconi looks like big trouble, i'll rollback 1.1.2 and try to fix on weekend.

**Comment by alessandrofrancesconi** [comment]
If can help, I'm using the Fluent Theme on my Avalonia app.

```
<Application.Styles>
    <FluentTheme Mode="Dark" />
</Application.Styles>
```

**Comment by sn4k3** [comment]
When i deal with Auto sizes i often have to hack the window to make it work with dynamic stuff, eg:

https://github.com/sn4k3/UVtools/blob/6cfedea4cc36200caab87301e0dd121e97ddc8f2/UVtools.WPF/Windows/ToolWindow.axaml.cs#L600

Ugly but will work in every os

**Comment by CreateLab** [comment]
@sn4k3 ty
not sure that helps but try

**Comment by sn4k3** [comment]
In my case is to make scrollviewer work otherwise it will overflow and the viewport have the wrong size to acommodate all teh content. But i have cases where i also have to use this, on TabControls for example.
