### ISSUE TITLE
Windows width is too small and can't resize

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUtils/MessageBox.Avalonia#63]
With the latest version the width of the window is too small and can't change?
Also can `Width`, `MinWidth`, `MinHeight` and `SizeToContent` properties be exposed and bindable?
Would be great to have a `MaxHeight` too, so we can limit to not overflow user screen height and possibly a vertical scrollviewer if not already there

If i set `CanResize = true` i can shrink the window, but not grow, somehow is limited to that width as shown on screenshot.

```C#
        public static async Task<ButtonResult> MessageBoxGeneric(this Window window, string message, string title = null, 
            ButtonEnum buttons = ButtonEnum.Ok, Icon icon = Icon.None, WindowStartupLocation location = WindowStartupLocation.CenterOwner, Style style = Style.None)
        {
            var messageBoxStandardWindow = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(
                new MessageBoxStandardParams
                {
                    ButtonDefinitions = buttons,
                    ContentTitle = title ?? window.Title,
                    ContentMessage = message,
                    Icon = icon,
                    Style = style,
                    WindowIcon = new WindowIcon(App.GetAsset("/Assets/Icons/UVtools.ico")),
                    WindowStartupLocation = location,
                    CanResize = false,
                    MaxWidth = window.GetScreenWorkingArea().Width - UserSettings.Instance.General.WindowsHorizontalMargin,
                    ShowInCenter = true
                });
            return await messageBoxStandardWindow.ShowDialog(window);
        }
```

![image](https://user-images.githubusercontent.com/113281/116733394-f8192580-a9e3-11eb-828e-710b478475b9.png)

Problem:
https://github.com/AvaloniaUtils/MessageBox.Avalonia/blob/c68a2a5c6290763cc8ecf229daf58eda59d2b1b1/src/MessageBox.Avalonia/Views/MsBoxStandardWindow.xaml#L9

It lost the binding

**Comment by appleneko2001** [comment]
There was my mistake I forgot restore the bindings so they are constant parameters now
but I approved and applied your PR #65, they was binded with view models again.

Another thing is your PR #65 has fixed this issue. Since this issue is trending about window width cannot be resized and width not binded with view model, I think we can close this issue now.
